services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    hostname: spark-master
    command: >
      bash -lc "
      /opt/spark/sbin/start-master.sh &&
      tail -f /opt/spark/logs/*master*.out"
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "7077:7077"   # Standalone master RPC
      - "8080:8080"   # Master UI
    volumes:
      - ./spark-data:/opt/spark/data
    networks:
      - sparknet

  spark-worker-1:
    image: apache/spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    command: >
      bash -lc "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*worker*.out"
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"   # Worker UI (optional)
    volumes:
      - ./spark_data:/opt/spark/data
    networks:
      - sparknet
  spark-worker-2:
    image: apache/spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    command: >
      bash -lc "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*worker*.out"
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8082:8081"   # Worker UI (optional)
    volumes:
      - ./spark-data:/opt/spark/data
    networks:
      - sparknet

  spark-connect-server:
    image: apache/spark:latest
    container_name: spark-connect-server
    hostname: spark-connect-server
    depends_on:
      - spark-master
    command: >
      bash -lc "
      /opt/spark/sbin/start-connect-server.sh --master spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*connect*.out"
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "15002:15002"   # Spark Connect server port
    volumes:
      - ./spark-data:/opt/spark/data
    networks:
      - sparknet

networks:
  sparknet:
    driver: bridge
