
services:
  spark-master:
    image: delta-spark-4.0.1:latest
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=MASTER
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "7077:7077"   # Standalone master RPC
      - "8080:8080"   # Master UI
      - "4040:4040"   # Application UI (optional)
      - "18080:18080"   # History server UI\
      - "15002:15002"   # Spark Connect server port

    volumes:
      - ../spark_cluster/home:/home
      - ../spark_cluster/spark-data:/opt/spark/data
      - ../spark_cluster/spark-events:/opt/spark/spark-events
      - ../spark_cluster/spark-conf:/opt/spark/conf
      - ../spark_cluster/warehouse:/opt/spark/warehouse
      - ../spark_cluster/.ivy2:/tmp/.ivy2.5.2
      - ../spark_cluster/delta-tables:/opt/spark/delta
    networks:
      - sparknet
  spark-worker-1:
    image: delta-spark-4.0.1:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"   # Worker UI (optional)
    volumes:
      - ../spark_cluster/home:/home
      - ../spark_cluster/spark-data:/opt/spark/data
      - ../spark_cluster/spark-events:/opt/spark/spark-events
      - ../spark_cluster/spark-conf:/opt/spark/conf
      - ../spark_cluster/worker-logs:/opt/spark/worker-logs
      - ../spark_cluster/warehouse:/opt/spark/warehouse
      - ../spark_cluster/delta-tables:/opt/spark/delta
      - ../spark_cluster/worker-data:/opt/spark/worker-data
    networks:
      - sparknet

  spark-worker-2:
    image: delta-spark-4.0.1:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8082:8082"   # Worker UI (optional)
    volumes:
      - ../spark_cluster/home:/home
      - ../spark_cluster/spark-data:/opt/spark/data
      - ../spark_cluster/spark-events:/opt/spark/spark-events
      - ../spark_cluster/spark-conf:/opt/spark/conf
      - ../spark_cluster/worker-logs:/opt/spark/worker-logs
      - ../spark_cluster/warehouse:/opt/spark/warehouse
      - ../spark_cluster/delta-tables:/opt/spark/delta
      - ../spark_cluster/worker-data:/opt/spark/worker-data
    networks:
      - sparknet

networks:
  sparknet:
    driver: bridge
