
services:
  spark-master:
    image: delta-spark:4.0.1
    container_name: spark-master
    hostname: spark-master
    command: /opt/spark/sbin/start-master.sh --properties-file /opt/spark/spark-conf/spark-master.conf
    environment:
      - SPARK_NO_DAEMONIZE=true
      - HADOOP_HOME=/opt/spark/hadoop
    ports:
      - "7077:7077"   # Standalone master RPC
      - "8080:8080"   # Master UI
      - "4040:4040"   # Application UI (optional)
    volumes:
      - ../spark_cluster/spark-data:/opt/spark/data
      - ../spark_cluster/spark-events:/opt/spark/spark-events
      - ../spark_cluster/spark-conf:/opt/spark/spark-conf
      - ../spark_cluster/warehouse:/opt/spark/warehouse
      - ../spark_cluster/.ivy2:/tmp/.ivy2.5.2
      - ../spark_cluster/delta-tables:/opt/spark/delta-tables
      - ../spark_cluster/hadoop:/opt/spark/hadoop
    networks:
      - sparknet
  spark-worker-1:
    image: delta-spark:4.0.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    command: /opt/spark/sbin/start-worker.sh --properties-file /opt/spark/spark-conf/spark-worker.conf spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_WORKER_EVENT_LOG_DIR=/opt/spark/spark-events
      - SPARK_WORKER_LOG_DIR=/opt/spark/worker-logs
    ports:
      - "8081:8081"   # Worker UI (optional)
    volumes:
      - ../spark_cluster/spark-data:/opt/spark/data
      - ../spark_cluster/spark-events:/opt/spark/spark-events
      - ../spark_cluster/spark-conf:/opt/spark/spark-conf
      - ../spark_cluster/worker-logs:/opt/spark/worker-logs
      - ../spark_cluster/warehouse:/opt/spark/warehouse
      - ../spark_cluster/delta-tables:/opt/spark/delta-tables
    networks:
      - sparknet

  spark-worker-2:
    image: delta-spark:4.0.1
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    command: /opt/spark/sbin/start-worker.sh --properties-file /opt/spark/spark-conf/spark-worker.conf spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_WORKER_EVENT_LOG_DIR=/opt/spark/spark-events
      - SPARK_WORKER_LOG_DIR=/opt/spark/worker-logs
    ports:
      - "8082:8082"   # Worker UI (optional)
    volumes:
      - ../spark_cluster/spark-data:/opt/spark/data
      - ../spark_cluster/spark-events:/opt/spark/spark-events
      - ../spark_cluster/spark-conf:/opt/spark/spark-conf
      - ../spark_cluster/worker-logs:/opt/spark/worker-logs
      - ../spark_cluster/warehouse:/opt/spark/warehouse
      - ../spark_cluster/delta-tables:/opt/spark/delta-tables
    networks:
      - sparknet

  spark-connect-server:
    image: delta-spark:4.0.1
    container_name: spark-connect-server
    hostname: spark-connect-server
    depends_on:
      - spark-master
    command: /opt/spark/sbin/start-connect-server.sh --properties-file /opt/spark/spark-conf/spark-connect-server.conf
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "15002:15002"   # Spark Connect server port
    volumes:
      - ../spark_cluster/spark-data:/opt/spark/data
      - ../spark_cluster/spark-events:/opt/spark/spark-events
      - ../spark_cluster/spark-conf:/opt/spark/spark-conf
      - ../spark_cluster/warehouse:/opt/spark/warehouse
      - ../spark_cluster/.ivy2:/tmp/.ivy2.5.2
      - ../spark_cluster/delta-tables:/opt/spark/delta-tables

    networks:
      - sparknet

  spark-history-server:
    image: delta-spark:4.0.1
    container_name: spark-history-server
    hostname: spark-history-server
    depends_on:
      - spark-master
    command: /opt/spark/sbin/start-history-server.sh  --properties-file /opt/spark/spark-conf/spark-history-server.conf
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "18080:18080"   # History server UI
    volumes:
      - ../spark_cluster/spark-data:/opt/spark/data
      - ../spark_cluster/spark-events:/opt/spark/spark-events
      - ../spark_cluster/spark-conf:/opt/spark/spark-conf
      - ../spark_cluster/.ivy2:/tmp/.ivy2.5.2
    networks:
      - sparknet

networks:
  sparknet:
    driver: bridge
