
services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    hostname: spark-master
    command: >
      bash -lc "
      /opt/spark/sbin/start-master.sh &&
      tail -f /opt/spark/logs/*master*.out"
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "7077:7077"   # Standalone master RPC
      - "8080:8080"   # Master UI
    networks:
      - sparknet

  spark-worker-1:
    image: apache/spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    command: >
      bash -lc "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*worker*.out"
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"   # Worker UI (optional)
    networks:
      - sparknet
  spark-worker-2:
    image: apache/spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    command: >
      bash -lc "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*worker*.out"
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8082:8081"   # Worker UI (optional)
    networks:
      - sparknet

  spark-connect:
    image: apache/spark:latest
    container_name: spark-connect
    hostname: spark-connect
    depends_on:
      - spark-master
      - spark-worker-1
    command: >
      bash -lc "
      /opt/spark/sbin/start-connect-server.sh
        --master spark://spark-master:7077
        --conf spark.connect.grpc.binding.address=0.0.0.0
        --conf spark.connect.grpc.binding.port=15002
      &&
      tail -f /opt/spark/logs/*connect*.out"
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "15002:15002" # Spark Connect gRPC
      - "4040:4040"   # First Spark app UI (optional; may increment)
    networks:
      - sparknet

networks:
  sparknet:
    driver: bridge
